# Gradle settings
# Increase memory available to Gradle, enable parallelism, and enable caching
org.gradle.jvmargs=-Xmx8G
org.gradle.configureondemand=true
org.gradle.parallel=true
org.gradle.caching=true

# Gradle plugins
kotlin_jvm_plugin_version=1.9.21
auto_include_plugin_version=1.3
cloche_plugin_version=0.11.6

# Mod
mod_group=io.github.steveplays28
mod_id=noisium
mod_version=2.5.0
mod_name=Noisium
mod_description=Optimises worldgen performance for a better gameplay experience.
mod_license=LGPL-3.0
mod_authors=Steveplays28
mod_url=https://www.curseforge.com/minecraft/mc-mods/noisium
mod_sources=https://github.com/Steveplays28/noisium
mod_issues=https://github.com/Steveplays28/noisium/issues

# Publishing properties
maven_organization=Steveplays28
curseforge_project_id=930207
modrinth_project_id=KuNKN7d2

# Dependencies
fabric_loader_version=0.16.14
mixin_extras_version=0.5.0-rc.2
